### ISSUE TITLE
Compiler fails if @import dependency cannot be found

### ISSUE THREAD

**Issue by spierobi** [dotless/dotless#220]
I've copied a less file into the dotless directory and tried to compile it to CSS.
The less file contains a reference to another less which was not copied.

I expected to see a compilation fail error due to the missing dependency.
However the compiler crashed with a windows error "dotless 1.3.0.5 has stopped working".

After that it throwed the expected exception in the console:
Unhandled Exception: System.IO.FileNotFoundException: You are importing a file ending in .less that cannot be found.
File name: 'styles/theme_default/general.less'
   at dotless.Core.Importers.Importer.Import(Import import)
   at dotless.Core.Parser.Tree.Import..ctor(String path, IImporter importer, Value features, Boolean isOnce)
   at dotless.Core.Parser.Tree.Import..ctor(Quoted path, IImporter importer, Value features, Boolean isOnce)
   at dotless.Core.Parser.Infrastructure.DefaultNodeProvider.Import(Quoted path, IImporter importer, Value features, Boolean isOnce, NodeLoc
ation location)
   at dotless.Core.Parser.Parsers.Import(Parser parser)
   at dotless.Core.Parser.Parsers.Directive(Parser parser)
   at dotless.Core.Parser.Parsers.Primary(Parser parser)
   at dotless.Core.Parser.Parser.Parse(String input, String fileName)
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
   at dotless.Compiler.FixImportPathDecorator.TransformToCss(String source, String fileName)
   at dotless.Compiler.Program.CompileImpl(ILessEngine engine, String inputFilePath, String outputFilePath)
   at dotless.Compiler.Program.<>c__DisplayClass6.<Main>b__2()
   at dotless.Compiler.Program.Main(String[] args)

Would it be possible to avoid the nasty windows crash for this kind of error?

**Comment by rytmis** [comment]
The current version no longer crashes, although the exception output is still somewhat sub-optimal.
