### ISSUE TITLE
Incomplete declaration causes NullReferenceException

### ISSUE THREAD

**Issue by BEllis** [dotless/dotless#287]
using the compiler in dotLess 1.3.1.0,

div {
    border-bottom: 
}

will produce,

Compilation failed: Object reference not set to an instance of an object.
   at dotless.Core.Parser.Parsers.Rule(Parser parser) in C:\dev\dotless\src\dotless.Core\Parser\Parsers.cs:line 1036
   at dotless.Core.Parser.Parsers.Primary(Parser parser) in C:\dev\dotless\src\dotless.Core\Parser\Parsers.cs:line 76
   at dotless.Core.Parser.Parsers.Block(Parser parser) in C:\dev\dotless\src\dotless.Core\Parser\Parsers.cs:line 962
   at dotless.Core.Parser.Parsers.Ruleset(Parser parser) in C:\dev\dotless\src\dotless.Core\Parser\Parsers.cs:line 1000
   at dotless.Core.Parser.Parsers.Primary(Parser parser) in C:\dev\dotless\src\dotless.Core\Parser\Parsers.cs:line 76
   at dotless.Core.Parser.Parser.Parse(String input, String fileName) in C:\dev\dotless\src\dotless.Core\Parser\Parser.cs:line 133
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName) inC:\dev\dotless\src\dotless.Core\Engine\LessEngine.cs:line 58
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName) in C:\dev\dotless\src\dotless.Core\Engine\ParameterDecorator.cs:line 29
   at dotless.Compiler.FixImportPathDecorator.TransformToCss(String source, String fileName) in c:\dev\dotless\src\dotless.Compiler\FixImportPathDecorator.cs:line 18
   at dotless.Compiler.Program.CompileImpl(ILessEngine engine, String inputFilePath, String outputFilePath) in c:\dev\dotless\src\dotless.Compiler\Program.cs:line 155

If this is by design, could the error be a bit more descriptive (line number / character number?)

**Comment by rytmis** [comment]
This is fixed in the latest release. It now reports an incomplete rule.

**Comment by uwes** [comment]
I have the same problem using dotless 1.4.1.0. When I'm trying to get the latest version with the fix (1.4.3. as I have read in a similar ticket) on the NuGet Console I get the following: 
'dotless 1.4.1.0' already installed.
Adding 'dotless 1.4.1.0' to www.
Successfully added 'dotless 1.4.1.0' to www.'

What am I doing wrong?

Thanks

**Comment by rytmis** [comment]
Try specifying the version number, e.g. `Install-Package dotless -Version 1.4.4.0`. You might also want to try out the latest released version, 1.5.1.

**Comment by uwes** [comment]
Thanks! Will try.

**Comment by uwes** [comment]
Thanks very much again for your quick response. This worked.
