### ISSUE TITLE
Dotless 1.5.1.0 plugins to Dotless.compiler.exe fail with ReflectionTypeLoadException

### ISSUE THREAD

**Issue by sea1jxr** [dotless/dotless#494]
I am wondering if the dotless.Core.dll has been ILMerged into dotless.compiler.exe and is causing some problems with the same type name but having different instances.  When I try to create a plugin that references dotless.Core lib for the IFunctionPlugin interface, it gets a ReflectionTypeLoadException

#### foo.cs
```C#
namespace Tests
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using dotless.Core.Plugins;

    [DisplayName("UtilPlugins")]
    public class UtilPlugins : IFunctionPlugin
    {
        public Dictionary<string, Type> GetFunctions()
        {
            return new Dictionary<string, Type>();
        }
    }
} 
```

using the following compile command
`csc /t:library /r:dotless.Core.dll foo.cs`

I place the foo.dll in the "plugins" directory below dotless.compiler.exe and run
`dotless.compiler.exe -l`

The result is this exception
```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at dotless.Core.Plugins.PluginFinder.GetConfigurators(Assembly assembly) in c:\projects\dotless\src\dotless.Core\Plugins\PluginFinder.cs:line 96
   at dotless.Core.Plugins.PluginFinder.GetConfigurators(Boolean scanPluginsFolder) in c:\projects\dotless\src\dotless.Core\Plugins\PluginFinder.cs:line 81
   at dotless.Compiler.Program.GetPluginConfigurators()
   at dotless.Compiler.Program.WritePluginList()
   at dotless.Compiler.Program.GetConfigurationFromArguments(List`1 arguments)
   at dotless.Compiler.Program.Main(String[] args)
```

**Comment by rytmis** [comment]
Yes, Core is ilmerge'd into the compiler executable. The issues regarding merging have been discussed before, and the general consensus is that we should stop doing that.
